language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
sudo: false
install: true
before_install:
  - pip install --user codecov
after_success:
  - codecov
  - mvn clean test jacoco:report coveralls:report